
INSERT INTO [dbo].[F_CREGLEMENT]
           ([CT_NumPayeur]
           ,[RG_Date]
           ,[RG_Reference]
           ,[RG_Libelle]
           ,[RG_Montant]
           ,[RG_MontantDev]
           ,[N_Reglement]
           ,[RG_Impute]
           ,[RG_Compta]
           ,[EC_No]
           ,[RG_Type]
           ,[RG_Cours]
           ,[N_Devise]
           ,[JO_Num]
           ,[RG_Impaye]
           ,[CG_Num]
           ,[RG_TypeReg]
           ,[RG_Heure]
           ,[RG_Piece]
           ,[CA_No]
           ,[CO_NoCaissier]
           ,[RG_Banque]
           ,[RG_Transfere]
           ,[RG_Cloture]
           ,[RG_Ticket]
           ,[RG_Souche]
           ,[CT_NumPayeurOrig]
           ,[RG_DateEchCont]
           ,[RG_MontantEcart]
           ,[RG_NoBonAchat]
           ,[RG_Valide]
           ,[RG_Anterieur]
           ,[RG_MontantCommission]
           ,[RG_MontantNet]
           ,[cbProt]
           ,[cbCreateur]
           ,[cbModification]
           ,[cbReplication]
           ,[cbFlag]
           ,[cbCreation]
           ,[cbHashVersion]
           ,[cbHashDate]
           ,[cbHashOrder])
     VALUES
           (@CT_NumPayeur
           ,@RG_Date
           ,@RG_Reference
           ,@RG_Libelle
           ,@RG_Montant
           ,@RG_MontantDev
           ,@N_Reglement
           ,@RG_Impute
           ,@RG_Compta
           ,@EC_No
           ,@RG_Type
           ,@RG_Cours
           ,@N_Devise
           ,@JO_Num
           ,@RG_Impaye
           ,@CG_Num
           ,@RG_TypeReg
           ,@RG_Heure
           ,@RG_Piece
           ,@CA_No
           ,@CO_NoCaissier
           ,@RG_Banque
           ,@RG_Transfere
           ,@RG_Cloture
           ,@RG_Ticket
           ,@RG_Souche
           ,@CT_NumPayeurOrig
           ,@RG_DateEchCont
           ,@RG_MontantEcart
           ,@RG_NoBonAchat
           ,@RG_Valide
           ,@RG_Anterieur
           ,@RG_MontantCommission
           ,@RG_MontantNet
           ,@cbProt
           ,@cbCreateur
           ,@RG_Date
           ,@cbReplication
           ,@cbFlag
           ,@RG_Date
           ,@cbHashVersion
           ,@RG_Date
           ,@cbHashOrder)










